/**
 * Render a `plan` result as a self-contained HTML page: the Mermaid roadmap
 * rendered visually, plus the scored slot table. Mermaid is pulled from a CDN at
 * view time, so the file is a single portable artifact (no build step, no deps
 * added to the CLI). Used by `lurq plan --html <path>` / `--open`.
 */
import type { PlanOutput } from '../mcp/plan';

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);
}

function slotRows(plan: PlanOutput): string {
  return plan.slots
    .map((s) => {
      const rec = s.recommended;
      const name = rec
        ? rec.repoUrl
          ? `<a href="${esc(rec.repoUrl)}" target="_blank" rel="noreferrer">${esc(rec.name)}</a>`
          : esc(rec.name)
        : '<span class="muted">— no match —</span>';
      const alts = s.alternatives.map((a) => esc(a.name)).join(', ') || '<span class="muted">—</span>';
      return `<tr>
        <td>${esc(s.need)}</td>
        <td><span class="layer">${esc(s.layer)}</span></td>
        <td class="pkg">${name}</td>
        <td class="num">${rec ? rec.healthScore : '—'}</td>
        <td>${rec ? esc(rec.confidence) : '—'}</td>
        <td class="alts">${alts}</td>
      </tr>`;
    })
    .join('\n');
}

export function renderPlanHtml(plan: PlanOutput): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>lurq plan — roadmap</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body { margin: 0; font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, sans-serif;
         background: #0b0b0f; color: #e7e7ea; padding: 2.5rem clamp(1rem, 5vw, 4rem); }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  h2 { font-size: 1rem; text-transform: uppercase; letter-spacing: .08em; color: #9a9aa6; margin: 2.5rem 0 .75rem; }
  .sub { color: #9a9aa6; margin: 0 0 1rem; max-width: 70ch; }
  .diagram { background: #141419; border: 1px solid #26262e; border-radius: 14px; padding: 1.5rem; overflow: auto; }
  table { width: 100%; border-collapse: collapse; margin-top: .5rem; }
  th, td { text-align: left; padding: .55rem .75rem; border-bottom: 1px solid #1e1e25; vertical-align: top; }
  th { font-size: .78rem; text-transform: uppercase; letter-spacing: .05em; color: #9a9aa6; }
  .pkg a { color: #d98cff; text-decoration: none; } .pkg a:hover { text-decoration: underline; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .muted { color: #6a6a76; } .alts { color: #b8b8c2; font-size: .92rem; }
  .layer { font-size: .8rem; color: #8ad; background: #15202b; border-radius: 6px; padding: .1rem .45rem; }
  footer { margin-top: 2.5rem; color: #6a6a76; font-size: .85rem; }
</style>
</head>
<body>
  <h1>lurq plan <span class="muted">· ${esc(plan.optimize)} · ${esc(plan.source)}${plan.framework ? ` · ${esc(plan.framework)} ecosystem` : ''}</span></h1>
  <p class="sub">${esc(plan.note)}</p>

  <h2>Roadmap</h2>
  <div class="diagram"><pre class="mermaid">${esc(plan.mermaid)}</pre></div>

  <h2>Components</h2>
  <table>
    <thead><tr><th>Component</th><th>Layer</th><th>Recommended</th><th>Health</th><th>Confidence</th><th>Alternatives</th></tr></thead>
    <tbody>
${slotRows(plan)}
    </tbody>
  </table>

  <footer>data as of ${esc(plan.dataAsOf)} · generated by lurq</footer>

  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true, theme: 'dark' });
  </script>
</body>
</html>
`;
}
